# Data Preprocessing

## Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing Dataset

In [ ]:
data_set=pd.read_csv("Covid_Data_new.csv")
data_set.head()

age body_temperature chronic_disease breathing_issue  \
0  10.0         Moderate              no              no   
1  12.0         Moderate              no              no   
2  15.0         Moderate              no              no   
3  10.0         Moderate              no              no   
4  13.0         Moderate              no              no   

   Blood O2 Level in Percentage Needed Hospitalization  Unnamed: 6  
0                          97.0                     No         NaN  
1                          97.0                     No         NaN  
2                          94.0                     No         NaN  
3                          97.0                     No         NaN  
4                          94.0                     No         NaN

In [ ]:
data_set.drop(columns="Unnamed: 6",inplace=True)

In [ ]:
data_set.head()

age body_temperature chronic_disease breathing_issue  \
0  10.0         Moderate              no              no   
1  12.0         Moderate              no              no   
2  15.0         Moderate              no              no   
3  10.0         Moderate              no              no   
4  13.0         Moderate              no              no   

   Blood O2 Level in Percentage Needed Hospitalization  
0                          97.0                     No  
1                          97.0                     No  
2                          94.0                     No  
3                          97.0                     No  
4                          94.0                     No

In [ ]:
X = data_set.iloc[:,0:5]
Y = data_set.iloc[:,-1]
print(X)
print(Y)

     age body_temperature chronic_disease breathing_issue  \
0   10.0         Moderate              no              no   
1   12.0         Moderate              no              no   
2   15.0         Moderate              no              no   
3   10.0         Moderate              no              no   
4   13.0         Moderate              no              no   
..   ...              ...             ...             ...   
65  86.0             High              no             yes   
66  61.0         Moderate              no             yes   
67  94.0             High             yes             yes   
68  81.0             High             yes             yes   
69  76.0             High             yes             yes   

    Blood O2 Level in Percentage  
0                           97.0  
1                           97.0  
2                           94.0  
3                           97.0  
4                           94.0  
..                           ...  
65                    

In [ ]:
X.values

array([[10.0, 'Moderate', 'no', 'no', 97.0],
       [12.0, 'Moderate', 'no', 'no', 97.0],
       [15.0, 'Moderate', 'no', 'no', 94.0],
       [10.0, 'Moderate', 'no', 'no', 97.0],
       [13.0, 'Moderate', 'no', 'no', 94.0],
       [12.0, 'Moderate', 'no', 'no', 97.0],
       [13.0, 'Moderate', 'no', 'no', 93.0],
       [15.0, 'Moderate', 'no', 'no', 92.0],
       [18.0, 'Moderate', 'no', 'no', 66.0],
       [19.0, 'Moderate', 'no', 'no', 92.0],
       [20.0, 'Moderate', 'no', 'no', 93.0],
       [17.0, 'Moderate', 'no', 'no', 93.0],
       [16.0, 'Moderate', 'no', 'no', 92.0],
       [18.0, 'Moderate', 'no', 'no', 93.0],
       [20.0, 'Moderate', 'no', 'no', 92.0],
       [25.0, 'Moderate', 'no', 'no', 93.0],
       [24.0, 'Moderate', 'no', 'no', 92.0],
       [26.0, 'High', 'no', 'no', 94.0],
       [28.0, 'Moderate', 'no', 'no', 99.0],
       [29.0, 'Moderate', 'no', 'no', 93.0],
       [30.0, 'Moderate', 'no', 'no', 62.0],
       [19.0, 'Moderate', 'no', 'no', 89.0],
       [25.0, 




## Handling Missing Data

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X.iloc[:, 0:1])
X.iloc[:,0:1]=imputer.transform(X.iloc[:,0:1])
X.values

array([[10.0, 'Moderate', 'no', 'no', 97.0],
       [12.0, 'Moderate', 'no', 'no', 97.0],
       [15.0, 'Moderate', 'no', 'no', 94.0],
       [10.0, 'Moderate', 'no', 'no', 97.0],
       [13.0, 'Moderate', 'no', 'no', 94.0],
       [12.0, 'Moderate', 'no', 'no', 97.0],
       [13.0, 'Moderate', 'no', 'no', 93.0],
       [15.0, 'Moderate', 'no', 'no', 92.0],
       [18.0, 'Moderate', 'no', 'no', 66.0],
       [19.0, 'Moderate', 'no', 'no', 92.0],
       [20.0, 'Moderate', 'no', 'no', 93.0],
       [17.0, 'Moderate', 'no', 'no', 93.0],
       [16.0, 'Moderate', 'no', 'no', 92.0],
       [18.0, 'Moderate', 'no', 'no', 93.0],
       [20.0, 'Moderate', 'no', 'no', 92.0],
       [25.0, 'Moderate', 'no', 'no', 93.0],
       [24.0, 'Moderate', 'no', 'no', 92.0],
       [26.0, 'High', 'no', 'no', 94.0],
       [28.0, 'Moderate', 'no', 'no', 99.0],
       [29.0, 'Moderate', 'no', 'no', 93.0],
       [30.0, 'Moderate', 'no', 'no', 62.0],
       [19.0, 'Moderate', 'no', 'no', 89.0],
       [25.0, 

In [ ]:
imputer.fit(X.iloc[:,4:5])
X.iloc[:,4:5]=imputer.transform(X.iloc[:,4:5])
X.values

array([[10.0, 'Moderate', 'no', 'no', 97.0],
       [12.0, 'Moderate', 'no', 'no', 97.0],
       [15.0, 'Moderate', 'no', 'no', 94.0],
       [10.0, 'Moderate', 'no', 'no', 97.0],
       [13.0, 'Moderate', 'no', 'no', 94.0],
       [12.0, 'Moderate', 'no', 'no', 97.0],
       [13.0, 'Moderate', 'no', 'no', 93.0],
       [15.0, 'Moderate', 'no', 'no', 92.0],
       [18.0, 'Moderate', 'no', 'no', 66.0],
       [19.0, 'Moderate', 'no', 'no', 92.0],
       [20.0, 'Moderate', 'no', 'no', 93.0],
       [17.0, 'Moderate', 'no', 'no', 93.0],
       [16.0, 'Moderate', 'no', 'no', 92.0],
       [18.0, 'Moderate', 'no', 'no', 93.0],
       [20.0, 'Moderate', 'no', 'no', 92.0],
       [25.0, 'Moderate', 'no', 'no', 93.0],
       [24.0, 'Moderate', 'no', 'no', 92.0],
       [26.0, 'High', 'no', 'no', 94.0],
       [28.0, 'Moderate', 'no', 'no', 99.0],
       [29.0, 'Moderate', 'no', 'no', 93.0],
       [30.0, 'Moderate', 'no', 'no', 62.0],
       [19.0, 'Moderate', 'no', 'no', 89.0],
       [25.0, 

## Encoding Categorical Data

### Encoding independent variables

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [ ]:
X

array([[0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [0.0, 1.0, 12.0, 'no', 'no', 97.0],
       [0.0, 1.0, 15.0, 'no', 'no', 94.0],
       [0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [0.0, 1.0, 13.0, 'no', 'no', 94.0],
       [0.0, 1.0, 12.0, 'no', 'no', 97.0],
       [0.0, 1.0, 13.0, 'no', 'no', 93.0],
       [0.0, 1.0, 15.0, 'no', 'no', 92.0],
       [0.0, 1.0, 18.0, 'no', 'no', 66.0],
       [0.0, 1.0, 19.0, 'no', 'no', 92.0],
       [0.0, 1.0, 20.0, 'no', 'no', 93.0],
       [0.0, 1.0, 17.0, 'no', 'no', 93.0],
       [0.0, 1.0, 16.0, 'no', 'no', 92.0],
       [0.0, 1.0, 18.0, 'no', 'no', 93.0],
       [0.0, 1.0, 20.0, 'no', 'no', 92.0],
       [0.0, 1.0, 25.0, 'no', 'no', 93.0],
       [0.0, 1.0, 24.0, 'no', 'no', 92.0],
       [1.0, 0.0, 26.0, 'no', 'no', 94.0],
       [0.0, 1.0, 28.0, 'no', 'no', 99.0],
       [0.0, 1.0, 29.0, 'no', 'no', 93.0],
       [0.0, 1.0, 30.0, 'no', 'no', 62.0],
       [0.0, 1.0, 19.0, 'no', 'no', 89.0],
       [0.0, 1.0, 25.0, 'no', 'yes', 86.0],
       [0.

### Encoding dependent variables

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [ ]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1])

## Splitting data into Test set & Training Set


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
print(X_train)

[[1.0 0.0 86.0 'yes' 'yes' 71.0]
 [0.0 1.0 35.0 'no' 'yes' 92.0]
 [1.0 0.0 75.0 'no' 'yes' 72.0]
 [1.0 0.0 42.0 'no' 'no' 92.0]
 [1.0 0.0 74.0 'yes' 'yes' 75.0]
 [1.0 0.0 62.0 'yes' 'yes' 68.0]
 [0.0 1.0 24.0 'no' 'no' 92.0]
 [0.0 1.0 48.0 'no' 'yes' 93.0]
 [1.0 0.0 58.0 'no' 'no' 70.0]
 [0.0 1.0 45.130434782608695 'yes' 'no' 90.0]
 [0.0 1.0 15.0 'no' 'no' 92.0]
 [0.0 1.0 70.0 'no' 'yes' 88.0]
 [1.0 0.0 52.0 'yes' 'yes' 80.0]
 [1.0 0.0 60.0 'yes' 'yes' 68.0]
 [1.0 0.0 54.0 'yes' 'yes' 70.0]
 [0.0 1.0 29.0 'no' 'no' 93.0]
 [1.0 0.0 78.0 'yes' 'yes' 71.0]
 [1.0 0.0 36.0 'yes' 'no' 90.0]
 [0.0 1.0 30.0 'yes' 'no' 86.0]
 [1.0 0.0 50.0 'yes' 'yes' 77.0]
 [0.0 1.0 18.0 'no' 'no' 93.0]
 [1.0 0.0 69.0 'no' 'yes' 53.0]
 [0.0 1.0 10.0 'no' 'no' 97.0]
 [1.0 0.0 26.0 'no' 'no' 94.0]
 [0.0 1.0 18.0 'no' 'no' 66.0]
 [1.0 0.0 62.0 'yes' 'yes' 69.0]
 [0.0 1.0 13.0 'no' 'no' 93.0]
 [1.0 0.0 40.0 'no' 'no' 92.0]
 [1.0 0.0 84.0 'yes' 'yes' 75.0]
 [1.0 0.0 76.0 'yes' 'yes' 80.0]
 [1.0 0.0 81.0 'yes' 'yes'

In [ ]:
print(X_test)

[[0.0 1.0 25.0 'no' 'yes' 86.0]
 [0.0 1.0 10.0 'no' 'no' 97.0]
 [1.0 0.0 68.0 'yes' 'no' 67.0]
 [0.0 1.0 13.0 'no' 'no' 94.0]
 [1.0 0.0 59.0 'yes' 'no' 68.0]
 [0.0 1.0 28.0 'no' 'no' 99.0]
 [0.0 1.0 20.0 'no' 'no' 93.0]
 [1.0 0.0 46.0 'yes' 'no' 91.0]
 [1.0 0.0 53.0 'yes' 'no' 55.0]
 [0.0 1.0 16.0 'no' 'no' 92.0]
 [1.0 0.0 38.0 'no' 'no' 75.0]
 [0.0 1.0 19.0 'no' 'no' 92.0]
 [1.0 0.0 94.0 'yes' 'yes' 64.0]
 [0.0 1.0 12.0 'no' 'no' 97.0]]


In [ ]:
print(Y_train)

[1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 0
 1 1 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1]


In [ ]:
print(Y_test)

[0 0 1 0 1 0 0 0 1 0 1 0 1 0]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,5:]=sc.fit_transform(X_train[:,5:])
X_test[:,5:]=sc.fit_transform(X_test[:,5:])

In [ ]:
print(X_train)

[[1.0 0.0 86.0 'yes' 'yes' -0.9941858494300261]
 [0.0 1.0 35.0 'no' 'yes' 0.9574354145081887]
 [1.0 0.0 75.0 'no' 'yes' -0.9012515035282064]
 [1.0 0.0 42.0 'no' 'no' 0.9574354145081887]
 [1.0 0.0 74.0 'yes' 'yes' -0.6224484658227472]
 [1.0 0.0 62.0 'yes' 'yes' -1.2729888871354853]
 [0.0 1.0 24.0 'no' 'no' 0.9574354145081887]
 [0.0 1.0 48.0 'no' 'yes' 1.0503697604100084]
 [1.0 0.0 58.0 'no' 'no' -1.087120195331846]
 [0.0 1.0 45.130434782608695 'yes' 'no' 0.7715667227045492]
 [0.0 1.0 15.0 'no' 'no' 0.9574354145081887]
 [0.0 1.0 70.0 'no' 'yes' 0.5856980309009097]
 [1.0 0.0 52.0 'yes' 'yes' -0.15777673631364833]
 [1.0 0.0 60.0 'yes' 'yes' -1.2729888871354853]
 [1.0 0.0 54.0 'yes' 'yes' -1.087120195331846]
 [0.0 1.0 29.0 'no' 'no' 1.0503697604100084]
 [1.0 0.0 78.0 'yes' 'yes' -0.9941858494300261]
 [1.0 0.0 36.0 'yes' 'no' 0.7715667227045492]
 [0.0 1.0 30.0 'yes' 'no' 0.3998293390972702]
 [1.0 0.0 50.0 'yes' 'yes' -0.4365797740191076]
 [0.0 1.0 18.0 'no' 'no' 1.0503697604100084]
 [1.0 0.0